### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by splitbrain**
Deprecate the old helper class in favor of a new `dokuwiki\plugin\sqlite\SQLiteDB` with a cleaner API and proper use of exceptions. Removal of all sqlite2 support, only PDO::sqlite is supported. Major code cleanup. Merge and cleanup of #65

### CODE REVIEW

**Comment by splitbrain** [comment]
@annda FYI you might want to look at this when debugging the struct migration stuff.

**Comment by splitbrain** [comment]
@solewniczak could you have a look at this? I think it should be ready to merge and should be backwards compatible to not break any existing plugins.

**Comment by splitbrain** [comment]
There's one remaining backward compatibility issue as discussed in https://github.com/cosmocode/sqlite/pull/76#issuecomment-1479332275

>> For me the migration fails with a PDO exception when trying to prepare the migration SQL ALTER TABLE ? ADD COLUMN published INT DEFAULT NULL The message says that the syntax is invalid and the offending part is the question mark.
>
> I had the similar issue. Generally the parameters can be data literals only (https://www.php.net/manual/en/pdo.prepare.php), so you cannot use it as column or table names. You must replace it with string concatenation.

I think the only way to fix this is to reintroduce the manual parameter quoting in the the deprecated helper. Plugins then need to update their code when moving to the new class.

**Comment by solewniczak** [comment]
> There's one remaining backward compatibility issue as discussed in [#76 (comment)](https://github.com/cosmocode/sqlite/pull/76#issuecomment-1479332275)
> 
> > > For me the migration fails with a PDO exception when trying to prepare the migration SQL ALTER TABLE ? ADD COLUMN published INT DEFAULT NULL The message says that the syntax is invalid and the offending part is the question mark.
> > 
> > 
> > I had the similar issue. Generally the parameters can be data literals only (https://www.php.net/manual/en/pdo.prepare.php), so you cannot use it as column or table names. You must replace it with string concatenation.
> 
> I think the only way to fix this is to reintroduce the manual parameter quoting in the the deprecated helper. Plugins then need to update their code when moving to the new class.

I remember that this issue was also present in the previous version of sqlite plugin. So in my opinion it can stay this way. But nevertheless it would be better if it was included in the SQLiteDB class.

**Comment by Klap-in** [comment]
For the migration from sqlite2 to PDO sqlite additional php extension/drivers were needed. So it would not make sense to have any support for the older for SQLite. However, is it this useful to add something that recognizes that someone uses the old version, and warn that it is not supported anymore, and explain or refer to explanation that an setup with older versions of SQLite plugin and php should be used to upgrade?

**Comment by solewniczak** [comment]
I fixed the issue with table and column names in my devel branch:  #77 by replacing the standard PDO parameters binding with the previous code.  Since the helper is only for backward compatibility I'll recommend to keep it this way. In the new SQLiteDB class we should provide other interface for binding table and column names.

**Comment by fjf2002** [comment]
> As pointed out in #78 GROUP_CONTENT is supported natively in sqlite, so we should drop our own implementation.

I think you meant `GROUP_CONCAT`.

**Comment by splitbrain** [comment]
This should now be ready to merge.

@annda I would like to run this branch on a bunch of our wikis first, to see if there are any issues with the backwards compatibility. Once we're satisfied that it works, we can merge and start migrating our plugins to use the new class.

**Comment by Klap-in** [comment]
Could you do please also a update of the documentation if it merged, with some guiding what is updated?

**Comment by splitbrain** [comment]
@Klap-in absolutely! docs will be updated as soon as this is merged.

**Comment by annda** [comment]
This PR dropped the custom implementation of `group_concat` but it was slightly different than the native one. Namely, it applied `array_unique()` on the data, which the native function does not do.

We rely on `group_concat` in the struct plugin when [building queries](https://github.com/cosmocode/dokuwiki-plugin-struct/blob/3bd3c3d43523b71ced9dc7a0927e755524daea8b/meta/AccessTable.php#LL523C32-L523C32). I haven't noticed any side effects of the change, except that a few tests fail. I'm not yet sure to handle this, probably by enforcing uniqueness somewhere in the code just after data has been fetched from the database.

Some other plugins also [use the function](https://codesearch.dokuwiki.org/search?project=plugin&project=template&full=group_concat&defs=&refs=&path=&hist=&type=&xrd=&nn=2&n=30) and may have to be adjusted.

**Comment by splitbrain** [comment]
The correct syntax to use when you don't want duplicates would be `GROUP_CONCAT(DISTINCT column)`. Unfortunately this is broken when you want to also set a delimiter as discussed here:

* https://sqlite.org/forum/info/221c2926f5e6f155
* https://stackoverflow.com/questions/18285713/how-to-avoid-duplication-in-group-concat
* https://sqlite-users.sqlite.narkive.com/EGUanjC8/sqlite-group-concat-with-distinct-bug

Workarounds on this limitation directly in the SQL are outlined above (sub selects) but I guess fixing it in code after retrieving the results is often easier.

I don't think it's worth to fix backwards compatibility for this and would rather have plugin authors adjust their code should it be affected.

**Comment by gerardnico** [comment]
Hy Andi,

I just made the migration. I had no time to check the new beauty structure.

During the update, just for your information, I got it by the cursor cache [data](https://github.com/cosmocode/sqlite/blob/master/helper.php#L253). 
I ended up copying the whole code because the `cache` variable is private.

Cheers
Nico

**Pull request merged**
